name: CMake on multiple platforms

on:
  push:
    branches: [ "publish" ]
  pull_request:
    branches: [ "publish" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: ubuntu-latest
            c_compiler: gcc
          - os: macos-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y zlib1g-dev libbz2-dev

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: |
          brew install zlib bzip2

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Set execute permissions on test scripts
        run: |
          chmod +x tests/*.sh
          chmod +x tests/*.pl

      - name: Configure CMake
        run: |
          cmake -B ${{ steps.strings.outputs.build-output-dir }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            ${{ runner.os == 'macOS' && '-DCMAKE_OSX_ARCHITECTURES=x86_64' || '' }} \
            -S ${{ github.workspace }}

      - name: Build
        run: |
          cmake --build "${{ steps.strings.outputs.build-output-dir }}" --config Release

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        continue-on-error: true
        run: |
          ctest --output-on-failure --verbose

      - name: Package Artifacts
        if: github.event_name == 'push' && github.ref == 'refs/heads/publish'
        run: |
          cd ${{ steps.strings.outputs.build-output-dir }}
          tar -czf artifact-${{ runner.os }}.tar.gz *

      - name: Upload Artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/publish'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-build
          path: ${{ steps.strings.outputs.build-output-dir }}/artifact-${{ runner.os }}.tar.gz
          retention-days: 5
          compression-level: 6
          if-no-files-found: error

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/publish'
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*-build'
          merge-multiple: true
          path: artifacts

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0           # Hardcoded version
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs').promises;
            const path = require('path');
            const { owner, repo } = context.repo;
            const release_id = '${{ steps.create_release.outputs.id }}';
            
            const files = await fs.readdir('./artifacts');
            for (const file of files) {
              const filePath = path.join('./artifacts', file);
              const fileData = await fs.readFile(filePath);
              const stats = await fs.stat(filePath);
            
              await github.rest.repos.uploadReleaseAsset({
                owner,
                repo,
                release_id,
                name: file,
                data: fileData,
                headers: {
                  'content-type': 'application/octet-stream',
                  'content-length': stats.size
                }
              });
            }
